version: '3'

services:
  server:
    build:
      context: .
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/alive"]

  client:
    build:
      context: .
    environment:
      START_AS_CLIENT: "true"
      BACKEND_ENDPOINT: "http://server:3000"
    depends_on:
      - server
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]